### PR TITLE
Endian-independent resource loading

### LINKED ISSUE #25: Endian-independent resource loading
Current loader assumes binary data endianness conforms architecture.

### PR DESCRIPTION
**Pull request by thelink2012**
Fixes #25 
Though it needs to be tested on a big endian machine.

h3dutCreateGeometryRes and h3dutCreateTGAImage were changed but not tested _(unless Knight/Chicago/Terrain uses them?)_.

Also I couldn't test _ColladaConv_ output since I don't have any proper _.dae_ over here. Isn't there a source for the knight model?

### CODE REVIEW

**Comment by zuck** [comment]
```
.../Projects/Horde3D/Horde3D/Source/Shared/utEndian.h:103:14: note:   template argument deduction/substitution failed:
.../Projects/Horde3D/Horde3D/Source/Horde3DUtils/main.cpp:651:59: note:   deduced conflicting types for parameter ‘T’ (‘unsigned int’ and ‘long unsigned int’)
   pData = elemset_le((uint32*)(pData), sizeof( float ) * 2); // stream element size
                                                           ^
Horde3D/Source/Horde3DUtils/CMakeFiles/Horde3DUtils.dir/build.make:54: recipe for target 'Horde3D/Source/Horde3DUtils/CMakeFiles/Horde3DUtils.dir/main.cpp.o' failed
make[2]: *** [Horde3D/Source/Horde3DUtils/CMakeFiles/Horde3DUtils.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:360: recipe for target 'Horde3D/Source/Horde3DUtils/CMakeFiles/Horde3DUtils.dir/all' failed
make[1]: *** [Horde3D/Source/Horde3DUtils/CMakeFiles/Horde3DUtils.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by thelink2012** [comment]
which compiler? 64 bits?

**Comment by zuck** [comment]
Yes, Ubuntu 15.04 x64.

**Comment by thelink2012** [comment]
That should do it _(not sure whether one receives notifications of new commits on a PR branch?)_

**Comment by zuck** [comment]
Great job, thank you!

**Pull request merged**
